public enum SFXType
{
    PlayerLStep,
    PlayerRStep,
    PlayerDodge,
    PlayerAttack,
    PlayerJump,
    PlayerHit,
    PlayerDie,
    SlimeAttack,
    SlimeHit,
    SlimeDie,
    BossMeleeAttack,
    BossChargeAttack,
    BossRangeAttack,
    BossArmorHit,
    BossHit,
    BossDie
}